insert into public.properties (id, name, slug, property_type, location, short_description, full_description, max_guests, bedrooms, beds, bathrooms, bed_arrangements, check_in_time, checkout_time, pet_policy, parking_type, nightly_price, cleaning_fee, pet_fee, extra_guest_fee, extra_guest_threshold, minimum_stay, weekly_discount, monthly_discount, house_rules, nearby_locations, unavailable_dates, latitude, longitude, published, featured, display_order, minimum_guests, maximum_adults, maximum_children, maximum_infants, maximum_pets)
values
('00000000-0000-0000-0000-000000000007', 'Serenity 7 - Whole', 'serenity-7', 'Entire furnished house', 'Pakenham, Victoria, Australia', 'A comfortable three-bedroom house for families, work crews and longer stays near Pakenham transport and shops.', 'Serenity 7 is a fully furnished private house arranged for practical, comfortable stays in Pakenham. The house sits beside the other Serenity houses, making it useful for groups that need separate houses in the same location.', 6, 3, 5, 2.5, '[{"room":"Bedroom 1","beds":"1 queen bed"},{"room":"Bedroom 2","beds":"2 single beds"},{"room":"Bedroom 3","beds":"2 single beds"}]', '3:00 PM', '11:00 AM', 'Pet-friendly. Pets must be declared before arrival.', 'Free parking', 240, 120, 45, 20, 4, 2, 8, 15, array['Check-in after 3:00 PM','Checkout before 11:00 AM','Maximum guest limit applies','Pets must be declared','No parties or events','No smoking inside','Quiet hours from 10:00 PM to 7:00 AM'], array['Beside Serenity 9 and Serenity 11','Pakenham town centre','Pakenham train station','Deep Creek Eco Playspace'], array['2026-08-12','2026-08-13','2026-08-14','2026-09-02','2026-09-03']::date[], -38.0702, 145.4742, true, true, 1, 1, 6, 6, 2, 2),
('00000000-0000-0000-0000-000000000009', 'Serenity 9 - Whole', 'serenity-9', 'Entire furnished house', 'Pakenham, Victoria, Australia', 'A larger four-bedroom furnished house with private bedrooms, parking and practical amenities for teams or families.', 'Serenity 9 is arranged for bigger families, work crews, project teams and relocating staff who need a private base in Pakenham. It is beside the other Serenity houses, so multiple families or teams can stay close while keeping their own private space.', 8, 4, 6, 2.5, '[{"room":"Bedroom 1","beds":"1 queen bed"},{"room":"Bedroom 2","beds":"2 single beds"},{"room":"Bedroom 3","beds":"2 single beds"},{"room":"Bedroom 4","beds":"1 single or configurable sleeping space"}]', '3:00 PM', '11:00 AM', 'Pet-friendly. Pets must be declared before arrival.', 'Free on-site parking', 290, 145, 45, 20, 6, 2, 10, 18, array['Check-in after 3:00 PM','Checkout before 11:00 AM','Maximum guest limit applies','Pets must be declared','No parties or events','No smoking inside','Quiet hours from 10:00 PM to 7:00 AM'], array['Beside Serenity 7 and Serenity 11','Pakenham town centre','Pakenham train station','Pakenham services'], array['2026-08-20','2026-08-21','2026-09-10','2026-09-11','2026-09-12']::date[], -38.0718, 145.4802, true, true, 2, 1, 8, 8, 2, 2),
('00000000-0000-0000-0000-000000000011', 'Serenity 11 - Whole', 'serenity-11', 'Entire furnished house', 'Pakenham, Victoria, Australia', 'A flexible four-bedroom house for business travellers, families and extended stays toward Gippsland.', 'Serenity 11 offers a practical furnished base in Pakenham for guests visiting the region, working locally or needing temporary accommodation. It is beside Serenity 7 and Serenity 9, which helps larger groups book nearby houses for the same dates when available.', 7, 4, 5, 2.5, '[{"room":"Bedroom 1","beds":"2 single beds"},{"room":"Bedroom 2","beds":"1 queen bed"},{"room":"Bedroom 3","beds":"1 queen bed"},{"room":"Bedroom 4","beds":"1 single bed"}]', '3:00 PM', '11:00 AM', 'Pet-friendly. Pets must be declared before arrival.', 'Free street parking', 270, 135, 45, 20, 5, 2, 8, 16, array['Check-in after 3:00 PM','Checkout before 11:00 AM','Maximum guest limit applies','Pets must be declared','No parties or events','No smoking inside','Quiet hours from 10:00 PM to 7:00 AM'], array['Beside Serenity 7 and Serenity 9','Deep Creek Eco Playspace','Pakenham train station','Pakenham South'], array['2026-08-28','2026-08-29','2026-09-18','2026-09-19']::date[], -38.0665, 145.486, true, true, 3, 1, 7, 7, 2, 2)
on conflict (id) do update set published = excluded.published, featured = excluded.featured, display_order = excluded.display_order, minimum_guests = excluded.minimum_guests, maximum_adults = excluded.maximum_adults, maximum_children = excluded.maximum_children, maximum_infants = excluded.maximum_infants, maximum_pets = excluded.maximum_pets, updated_at = timezone('utc', now());

insert into public.amenities (property_id, name, display_order)
select p.id, a.name, a.display_order
from (values
  ('serenity-7', 'Self check-in with key safe', 1), ('serenity-7', 'Wi-Fi', 2), ('serenity-7', 'Fully equipped kitchen', 3), ('serenity-7', 'Laundry facilities', 4), ('serenity-7', 'Free parking', 5), ('serenity-7', 'Netflix', 6), ('serenity-7', 'Heating', 7), ('serenity-7', 'Air conditioning', 8),
  ('serenity-9', 'Self check-in with key safe', 1), ('serenity-9', 'Wi-Fi', 2), ('serenity-9', 'Fully equipped kitchen', 3), ('serenity-9', 'Laundry facilities', 4), ('serenity-9', 'Free on-site parking', 5), ('serenity-9', 'Netflix', 6), ('serenity-9', 'Heating', 7), ('serenity-9', 'Air conditioning', 8),
  ('serenity-11', 'Self check-in with key safe', 1), ('serenity-11', 'Wi-Fi', 2), ('serenity-11', 'Fully equipped kitchen', 3), ('serenity-11', 'Laundry facilities', 4), ('serenity-11', 'Free street parking', 5), ('serenity-11', 'Netflix', 6), ('serenity-11', 'Heating', 7), ('serenity-11', 'Air conditioning', 8)
) as a(slug, name, display_order)
join public.properties p on p.slug = a.slug
where not exists (select 1 from public.amenities existing where existing.property_id = p.id and existing.name = a.name);

-- Property photos are intentionally not seeded with demo URLs. Upload licensed
-- property imagery through the admin dashboard into Supabase Storage instead.

insert into public.homepage_content (page_key, content, published)
values ('home', '{"hero_heading":"Furnished whole-house stays in Pakenham","hero_subtitle":"Book spacious, fully equipped private houses in Victoria for families, corporate stays, contractors, and relocations.","hero_cta_label":"Browse Houses","hero_cta_href":"/houses","faq_heading":"Good to know before arrival.","faq_description":"Clear answers for families, business travellers, contractors, and longer-stay guests.","faqs":[{"question":"How do I reserve a house online?","answer":"Choose your dates, select a Serenity house, and follow the direct booking steps. Our team will support you if you need a multi-house or longer-stay arrangement."},{"question":"Do guests need to create an account?","answer":"No. You can request a stay directly and receive the booking and check-in details by email."},{"question":"Do you display exact street addresses publicly?","answer":"For guest privacy and security, the full address and access instructions are shared after your booking is confirmed."},{"question":"How does Stripe payment work?","answer":"Payments are handled securely through Stripe. Your booking confirmation will show the amount and payment status in Australian Dollars."},{"question":"Are prices shown in Australian Dollars (AUD)?","answer":"Yes. Serenity Stays prices are shown and charged in Australian Dollars."},{"question":"Can a company pay via tax invoice or PO?","answer":"Yes. Contact us with your company details and stay requirements so we can confirm the best direct-booking arrangement."},{"question":"Can we book all three houses beside each other?","answer":"Yes, when availability allows. Contact us so we can coordinate adjacent houses for your group or project team."},{"question":"What time is check-in and checkout?","answer":"Check-in is available from 3:00 PM and checkout is before 11:00 AM, unless another arrangement has been confirmed with our team."},{"question":"How do guests access key safe instructions?","answer":"Keyless self-check-in details are sent before arrival once your booking has been confirmed and the required guest information is complete."},{"question":"Are pets and parking included?","answer":"Amenities and house rules vary by property. Review the house details and let us know about any pet or parking requirements before booking."}]}'::jsonb, true)
on conflict (page_key) do nothing;
