export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      properties: {
        Row: {
          id: string;
          name: string;
          slug: string;
          property_type: string;
          location: string;
          short_description: string;
          full_description: string;
          max_guests: number;
          bedrooms: number;
          beds: number;
          bathrooms: number;
          bed_arrangements: Json;
          check_in_time: string;
          checkout_time: string;
          pet_policy: string;
          parking_type: string;
          nightly_price: number;
          cleaning_fee: number;
          pet_fee: number;
          extra_guest_fee: number;
          extra_guest_threshold: number;
          minimum_stay: number;
          maximum_stay: number;
          minimum_guests: number;
          maximum_adults: number;
          maximum_children: number;
          maximum_infants: number;
          maximum_pets: number;
          minimum_advance_notice_days: number;
          maximum_advance_booking_days: number;
          same_day_booking_allowed: boolean;
          weekend_booking_allowed: boolean;
          instant_booking_enabled: boolean;
          booking_request_required: boolean;
          pets_allowed: boolean;
          corporate_booking_allowed: boolean;
          minimum_corporate_stay: number;
          minimum_corporate_houses: number;
          maximum_corporate_houses: number;
          adjacent_houses_allowed: boolean;
          long_term_stays_allowed: boolean;
          corporate_discount: number;
          corporate_approval_required: boolean;
          corporate_deposit_required: boolean;
          corporate_online_payment: boolean;
          gst_invoice_available: boolean;
          corporate_instructions: string;
          weekly_discount: number;
          monthly_discount: number;
          house_rules: string[];
          nearby_locations: string[];
          unavailable_dates: string[];
          latitude: number;
          longitude: number;
          published: boolean;
          featured: boolean;
          display_order: number;
          created_at: string;
          updated_at: string;
          listing_details: Json;
          listing_title: string;
          kitchen_facilities: string;
          laundry_facilities: string;
          wifi_information: string;
          workspace_information: string;
          heating_cooling: string;
          self_check_in_details: string;
          safety_information: string;
          cancellation_policy: string;
          corporate_information: string;
        };
        Insert: Partial<Database["public"]["Tables"]["properties"]["Row"]> & Pick<Database["public"]["Tables"]["properties"]["Row"], "name" | "slug">;
        Update: Partial<Database["public"]["Tables"]["properties"]["Row"]>;
        Relationships: [];
      };
      property_images: {
        Row: {
          id: string;
          property_id: string;
          storage_path: string | null;
          external_url: string | null;
          alt_text: string;
          display_order: number;
          category: string;
          category_label: string;
          category_description: string;
          is_cover: boolean;
          is_visible: boolean;
          is_placeholder: boolean;
          original_filename: string;
          file_size: number | null;
          mime_type: string;
          width: number | null;
          height: number | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Partial<Database["public"]["Tables"]["property_images"]["Row"]> & Pick<Database["public"]["Tables"]["property_images"]["Row"], "property_id" | "alt_text">;
        Update: Partial<Database["public"]["Tables"]["property_images"]["Row"]>;
        Relationships: [];
      };
      property_photo_categories: {
        Row: {
          id: string;
          property_id: string;
          category: string;
          category_label: string;
          category_description: string;
          display_order: number;
          is_visible: boolean;
          no_photo_available: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: Partial<Database["public"]["Tables"]["property_photo_categories"]["Row"]> & Pick<Database["public"]["Tables"]["property_photo_categories"]["Row"], "property_id" | "category" | "category_label">;
        Update: Partial<Database["public"]["Tables"]["property_photo_categories"]["Row"]>;
        Relationships: [];
      };
      property_reviews: {
        Row: {
          id: string;
          property_id: string;
          reviewer_name: string;
          review_text: string;
          rating: number;
          review_date: string | null;
          review_date_label: string | null;
          source: string;
          source_review_id: string;
          display_order: number;
          published: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: Partial<Database["public"]["Tables"]["property_reviews"]["Row"]> & Pick<Database["public"]["Tables"]["property_reviews"]["Row"], "property_id" | "reviewer_name" | "review_text" | "source_review_id">;
        Update: Partial<Database["public"]["Tables"]["property_reviews"]["Row"]>;
        Relationships: [];
      };
      property_date_prices: {
        Row: {
          id: string;
          property_id: string;
          price_date: string;
          nightly_price: number;
          label: string;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: Partial<Database["public"]["Tables"]["property_date_prices"]["Row"]> & Pick<Database["public"]["Tables"]["property_date_prices"]["Row"], "property_id" | "price_date" | "nightly_price">;
        Update: Partial<Database["public"]["Tables"]["property_date_prices"]["Row"]>;
        Relationships: [];
      };
      amenities: {
        Row: { id: string; property_id: string; name: string; display_order: number; created_at: string };
        Insert: Partial<Database["public"]["Tables"]["amenities"]["Row"]> & Pick<Database["public"]["Tables"]["amenities"]["Row"], "property_id" | "name">;
        Update: Partial<Database["public"]["Tables"]["amenities"]["Row"]>;
        Relationships: [];
      };
      bookings: {
        Row: {
          id: string;
          reference: string;
          property_id: string;
          check_in: string;
          checkout: string;
          adults: number;
          children: number;
          infants: number;
          pets: number;
          guest_details: Json;
          corporate_details: Json;
          price_breakdown: Json;
          total: number;
          currency: string;
          payment_status: string;
          booking_status: string;
          stripe_checkout_session_id: string | null;
          stripe_payment_intent_id: string | null;
          promotion_id: string | null;
          promotion_code: string | null;
          promotion_discount: number;
          promotion_redemption_id: string | null;
          booking_type: "standard" | "corporate" | "admin";
          booking_source: "website" | "corporate_page" | "admin" | "enquiry" | "airbnb" | "vrbo" | "stayz";
          enquiry_id: string | null;
          group_reference: string | null;
          idempotency_key: string | null;
          internal_notes: string;
          created_by_admin: string | null;
          notes: string;
          created_at: string;
          updated_at: string;
        };
        Insert: Partial<Database["public"]["Tables"]["bookings"]["Row"]> & Pick<Database["public"]["Tables"]["bookings"]["Row"], "reference" | "property_id" | "check_in" | "checkout">;
        Update: Partial<Database["public"]["Tables"]["bookings"]["Row"]>;
        Relationships: [];
      };
      promotions: {
        Row: {
          id: string;
          name: string;
          badge_text: string;
          message: string;
          mobile_message: string;
          code: string;
          discount_type: "percentage" | "fixed_aud";
          discount_value: number;
          starts_at: string | null;
          ends_at: string | null;
          max_redemptions: number | null;
          successful_redemptions: number;
          reserved_redemptions: number;
          minimum_booking_amount: number;
          minimum_nights: number;
          applicable_property_ids: string[];
          applies_to_corporate: boolean;
          stackable: boolean;
          restore_on_refund: boolean;
          active: boolean;
          published: boolean;
          header_visible: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: Partial<Database["public"]["Tables"]["promotions"]["Row"]> & Pick<Database["public"]["Tables"]["promotions"]["Row"], "name" | "code" | "discount_type" | "discount_value">;
        Update: Partial<Database["public"]["Tables"]["promotions"]["Row"]>;
        Relationships: [];
      };
      promotion_redemptions: {
        Row: {
          id: string;
          promotion_id: string;
          booking_id: string;
          stripe_checkout_session_id: string | null;
          discount_amount: number;
          status: "pending" | "confirmed" | "released" | "refunded";
          created_at: string;
          updated_at: string;
        };
        Insert: Partial<Database["public"]["Tables"]["promotion_redemptions"]["Row"]> & Pick<Database["public"]["Tables"]["promotion_redemptions"]["Row"], "promotion_id" | "booking_id">;
        Update: Partial<Database["public"]["Tables"]["promotion_redemptions"]["Row"]>;
        Relationships: [];
      };
      calendar_connections: {
        Row: {
          id: string;
          property_id: string;
          platform: "direct" | "airbnb" | "vrbo" | "stayz";
          connection_type: "export" | "import";
          external_calendar_url: string | null;
          export_token_hash: string | null;
          is_enabled: boolean;
          last_synced_at: string | null;
          last_attempt_at: string | null;
          last_success_at: string | null;
          last_error: string;
          last_imported_event_count: number;
          sync_frequency_minutes: number;
          sync_status: "not_configured" | "pending" | "success" | "error" | "conflict";
          created_at: string;
          updated_at: string;
        };
        Insert: Partial<Database["public"]["Tables"]["calendar_connections"]["Row"]> & Pick<Database["public"]["Tables"]["calendar_connections"]["Row"], "property_id" | "platform" | "connection_type">;
        Update: Partial<Database["public"]["Tables"]["calendar_connections"]["Row"]>;
        Relationships: [];
      };
      calendar_events: {
        Row: {
          id: string;
          property_id: string;
          connection_id: string | null;
          source_platform: "direct" | "airbnb" | "vrbo" | "stayz";
          external_event_id: string;
          start_date: string;
          end_date: string;
          status: "active" | "cancelled" | "stale";
          summary: string;
          block_reason: "maintenance" | "owner_use" | "cleaning" | "preparation" | "renovation" | "private_booking" | "other" | null;
          internal_note: string;
          is_blocking: boolean;
          last_seen_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Partial<Database["public"]["Tables"]["calendar_events"]["Row"]> & Pick<Database["public"]["Tables"]["calendar_events"]["Row"], "property_id" | "source_platform" | "external_event_id" | "start_date" | "end_date">;
        Update: Partial<Database["public"]["Tables"]["calendar_events"]["Row"]>;
        Relationships: [];
      };
      enquiries: {
        Row: {
          id: string;
          reference: string;
          company_name: string;
          contact_name: string;
          email: string;
          phone: string;
          arrival: string | null;
          departure: string | null;
          guests: string;
          houses_needed: string;
          purpose: string;
          notes: string;
          status: "new" | "contacted" | "pending_approval" | "approved" | "declined" | "converted";
          property_ids: string[];
          abn: string;
          purchase_order: string;
          invoice_requested: boolean;
          internal_notes: string;
          source: "corporate_page" | "admin";
          idempotency_key: string | null;
          converted_at: string | null;
          conversion_group_reference: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Partial<Database["public"]["Tables"]["enquiries"]["Row"]> & Pick<Database["public"]["Tables"]["enquiries"]["Row"], "company_name" | "contact_name" | "email">;
        Update: Partial<Database["public"]["Tables"]["enquiries"]["Row"]>;
        Relationships: [];
      };
      homepage_content: { Row: Record<string, unknown>; Insert: Record<string, unknown>; Update: Record<string, unknown>; Relationships: [] };
      homepage_hero_media: {
        Row: {
          id: string;
          storage_path: string;
          public_url: string;
          media_type: "image" | "video";
          mime_type: string;
          file_size: number;
          alt_text: string;
          caption: string;
          display_order: number;
          active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: Partial<Database["public"]["Tables"]["homepage_hero_media"]["Row"]> & Pick<Database["public"]["Tables"]["homepage_hero_media"]["Row"], "storage_path" | "public_url" | "media_type" | "mime_type" | "file_size">;
        Update: Partial<Database["public"]["Tables"]["homepage_hero_media"]["Row"]>;
        Relationships: [];
      };
      site_settings: { Row: Record<string, unknown>; Insert: Record<string, unknown>; Update: Record<string, unknown>; Relationships: [] };
      admin_users: { Row: { user_id: string; email: string; role: "admin" | "editor" | "super_admin"; active: boolean; created_at: string }; Insert: Partial<Database["public"]["Tables"]["admin_users"]["Row"]>; Update: Partial<Database["public"]["Tables"]["admin_users"]["Row"]>; Relationships: [] };
    };
    Views: Record<string, never>;
    Functions: {
      claim_first_admin: { Args: { p_user_id: string; p_email: string }; Returns: boolean };
      reserve_promotion_redemption: { Args: { p_promotion_id: string; p_booking_id: string; p_code: string; p_discount_amount: number }; Returns: string };
      confirm_promotion_redemption: { Args: { p_redemption_id: string; p_booking_id: string; p_session_id: string }; Returns: undefined };
      release_promotion_redemption: { Args: { p_booking_id: string }; Returns: undefined };
      restore_promotion_redemption: { Args: { p_redemption_id: string }; Returns: undefined };
      create_booking_group: {
        Args: { p_rows: Json; p_group_reference?: string | null; p_enquiry_id?: string | null; p_idempotency_key?: string | null };
        Returns: Database["public"]["Tables"]["bookings"]["Row"][];
      };
    };
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};
