"use client";

/* The CMS reads flexible Supabase rows, so the boundary is intentionally defensive. */

import HomepageHeroMediaEditor from "@/src/components/HomepageHeroMediaEditor";
import { CMS_LIMITS } from "@/src/lib/cmsValidation";
import { Building2, ChevronDown, ChevronUp, Globe2, MessageSquare, Plus, Save, Search, Star, Trash2 } from "lucide-react";
import { useState } from "react";

import { AdminBadge as StatusBadge } from "@/src/components/admin/AdminUI";

import { CharacterField, EmptyState, FormGroup, IconButton, moveItem, PageHeader } from "./AdminFields";
import { Benefit, HomepageDraft, HomepageFaq, HomepageSectionKey, Row } from "./AdminModels";
export function HomepageSectionsEditor({ baseline, homepage, setHomepage, published, saveSection, saving, properties, toggleFeatured }: { baseline: HomepageDraft; homepage: HomepageDraft; setHomepage: (value: HomepageDraft) => void; published: boolean; saveSection: (section: HomepageSectionKey, published: boolean) => Promise<void>; saving: boolean; properties: Row[]; toggleFeatured: (property: Row) => Promise<void> }) {
  const [activeSection, setActiveSection] = useState<HomepageSectionKey>("hero");
  const sectionKeys: Record<HomepageSectionKey, string[]> = { hero: ["hero_"], search: [], featured: ["featured_"], benefits: ["benefits"], corporate: ["corporate_"], location: ["location_"], faqs: ["faq"], cta: ["final_cta_"] };
  const dirtySections = Object.fromEntries(Object.entries(sectionKeys).map(([section,prefixes]) => [section, Object.keys(homepage).some(key => prefixes.some(prefix => key.startsWith(prefix)) && JSON.stringify(homepage[key as keyof HomepageDraft]) !== JSON.stringify(baseline[key as keyof HomepageDraft]))])) as Record<HomepageSectionKey, boolean>;
  const update = (key: keyof HomepageDraft, value: unknown, _section: HomepageSectionKey) => {
    void _section;
    setHomepage({ ...homepage, [key]: value });
  };
  const updateBenefit = (index: number, key: keyof Benefit, value: string) => {
    setHomepage({ ...homepage, benefits: homepage.benefits.map((benefit, itemIndex) => itemIndex === index ? { ...benefit, [key]: value } : benefit) });
  };
  const updateFaq = (index: number, key: keyof HomepageFaq, value: string) => {
    setHomepage({ ...homepage, faqs: homepage.faqs.map((faq, itemIndex) => itemIndex === index ? { ...faq, [key]: value } : faq) });
  };
  const saveCurrent = async (shouldPublish: boolean) => {
    try {
      await saveSection(activeSection, shouldPublish);
    } catch {
      // The parent displays the server error notification.
    }
  };
  const sectionMeta: Array<{ id: HomepageSectionKey; label: string; description: string }> = [
    { id: "hero", label: "Hero", description: "The first message and calls to action." },
    { id: "search", label: "Search", description: "The date and guest search control." },
    { id: "featured", label: "Featured houses", description: "The featured property section and selection." },
    { id: "benefits", label: "Benefits", description: "Amenities and trust points shown to guests." },
    { id: "corporate", label: "Corporate stays", description: "The business accommodation call to action." },
    { id: "location", label: "Location", description: "The Pakenham area map section." },
    { id: "faqs", label: "FAQs", description: "Answers that help guests book with confidence." },
    { id: "cta", label: "Final CTA", description: "The final booking prompt at the foot of the homepage." },
  ];
  const activeMeta = sectionMeta.find((item) => item.id === activeSection) ?? sectionMeta[0];

  return <>
    <PageHeader eyebrow="Homepage CMS" title="Edit the homepage section by section" description="Choose one area, update the plain-language fields, then save only that section." action={<StatusBadge label={published ? "Published" : "Draft"} tone={published ? "success" : "neutral"} />} />
    <div className="homepage-cms-grid">
      <div className="min-w-0">
        <nav className="homepage-cms-tabs" aria-label="Homepage sections">
          {sectionMeta.map((section) => <button key={section.id} type="button" className={`homepage-cms-tab ${activeSection === section.id ? "is-active" : ""}`} onClick={() => setActiveSection(section.id)}><span>{section.label}</span>{dirtySections[section.id] && <span className="homepage-cms-unsaved">Unsaved</span>}</button>)}
        </nav>
        <section className="admin-card homepage-cms-panel bg-[var(--admin-surface)] p-5 sm:p-7">
          <div className="flex flex-wrap items-start justify-between gap-4 border-b border-[var(--admin-border)] pb-5">
            <div><p className="text-sm font-medium text-[var(--admin-text)]">Homepage section</p><h2 className="mt-2 text-2xl font-semibold">{activeMeta.label}</h2><p className="mt-2 max-w-2xl text-sm leading-relaxed text-[var(--admin-muted)]">{activeMeta.description}</p></div>
            {dirtySections[activeSection] ? <StatusBadge label="Unsaved changes" tone="danger" /> : <StatusBadge label={activeSection === "search" ? "Functional section" : "Saved"} tone="neutral" />}
          </div>
          {activeSection === "hero" && <div className="mt-6 grid gap-5"><FormGroup title="Hero message" description="Edit the headline, supporting line, and primary call to action shown over the homepage image."><CharacterField label="Hero headline" value={homepage.hero_heading} onChange={(value) => update("hero_heading", value, "hero")} limit={CMS_LIMITS.hero_heading} /><CharacterField label="Hero supporting line" value={homepage.hero_subtitle} onChange={(value) => update("hero_subtitle", value, "hero")} limit={CMS_LIMITS.hero_subtitle} /><div className="grid gap-4 sm:grid-cols-2"><CharacterField label="Button label" value={homepage.hero_cta_label} onChange={(value) => update("hero_cta_label", value, "hero")} limit={CMS_LIMITS.button_label} /><CharacterField label="Button link" value={homepage.hero_cta_href} onChange={(value) => update("hero_cta_href", value, "hero")} limit={CMS_LIMITS.hero_cta_href} /></div><CharacterField label="Legacy image caption" value={homepage.hero_image_caption} onChange={(value) => update("hero_image_caption", value, "hero")} limit={CMS_LIMITS.hero_image_caption} help="Kept for existing homepage content; dedicated media captions are edited below." /></FormGroup><HomepageHeroMediaEditor /></div>}
           {activeSection === "search" && <div className="mt-6 rounded-xl border border-[var(--admin-border)] bg-[var(--admin-surface-alt)] p-5"><Search size={22} className="text-[var(--admin-text)]" /><h3 className="mt-3 text-lg font-semibold">Guest search and booking dates</h3><p className="mt-2 text-sm leading-relaxed text-[var(--admin-muted)]">This is the live booking search control. It uses Australia/Melbourne dates and does not currently have editable marketing copy. Booking behaviour remains unchanged.</p><div className="mt-5 grid gap-3 sm:grid-cols-3"><div className="rounded-xl bg-[var(--admin-surface)] p-4"><p className="text-sm font-medium text-[var(--admin-muted)]">Check-in</p><p className="mt-1 font-medium">Arrival date</p></div><div className="rounded-xl bg-[var(--admin-surface)] p-4"><p className="text-sm font-medium text-[var(--admin-muted)]">Checkout</p><p className="mt-1 font-medium">Departure date</p></div><div className="rounded-xl bg-[var(--admin-surface)] p-4"><p className="text-sm font-medium text-[var(--admin-muted)]">Guests</p><p className="mt-1 font-medium">Guest count</p></div></div></div>}
          {activeSection === "featured" && <div className="mt-6 grid gap-5"><FormGroup title="Featured houses heading" description="This heading introduces the homes guests can browse first."><CharacterField label="Section heading" value={homepage.featured_heading} onChange={(value) => update("featured_heading", value, "featured")} limit={CMS_LIMITS.section_heading} /><CharacterField label="Section description" value={homepage.featured_description} onChange={(value) => update("featured_description", value, "featured")} limit={CMS_LIMITS.section_description} textarea /></FormGroup><div className="rounded-xl border border-[var(--admin-border)] bg-[var(--admin-surface-alt)] p-5"><div className="flex items-start justify-between gap-3"><div><h3 className="text-lg font-semibold">Choose featured houses</h3><p className="mt-1 text-sm text-[var(--admin-muted)]">Changes apply to the public property grid immediately after the house is saved.</p></div><Building2 className="text-[var(--admin-text)]" size={22} /></div><div className="mt-4 grid gap-3 sm:grid-cols-3">{properties.map((property) => <button key={property.id} type="button" aria-pressed={Boolean(property.featured)} disabled={saving} onClick={() => void toggleFeatured(property)} className={`rounded-xl border p-4 text-left transition-colors ${property.featured ? "border-[var(--admin-border)] bg-[var(--admin-accent)] text-[var(--admin-on-accent)]" : "border-[var(--admin-border)] bg-[var(--admin-surface)] text-[var(--admin-text)] hover:bg-[var(--admin-surface-alt)]"}`}><span className="block text-sm font-semibold">{property.name}</span><span className="mt-1 block text-sm opacity-80">{property.featured ? "Featured on homepage" : "Not featured"}</span></button>)}</div></div></div>}
          {activeSection === "benefits" && <div className="mt-6 grid gap-5"><FormGroup title="Benefits introduction" description="Explain the practical comforts included with a whole-house stay."><CharacterField label="Section heading" value={homepage.benefits_heading} onChange={(value) => update("benefits_heading", value, "benefits")} limit={CMS_LIMITS.section_heading} /><CharacterField label="Section description" value={homepage.benefits_description} onChange={(value) => update("benefits_description", value, "benefits")} limit={CMS_LIMITS.section_description} textarea /></FormGroup><div className="rounded-xl border border-[var(--admin-border)] bg-[var(--admin-surface-alt)] p-4"><div className="flex items-start justify-between gap-3"><div><h3 className="text-lg font-semibold">Amenity and trust cards</h3><p className="mt-1 text-sm text-[var(--admin-muted)]">Add, remove, and reorder the cards used in the benefits row.</p></div><button type="button" className="admin-button inline-flex min-h-10 items-center gap-2 px-3 text-sm" onClick={() => { setHomepage({ ...homepage, benefits: [...homepage.benefits, { title: "", description: "" }] }); }}><Plus size={15} /> Add benefit</button></div><div className="mt-4 grid gap-3">{homepage.benefits.map((benefit, index) => <div key={`benefit-${index}`} className="rounded-xl border border-[var(--admin-border)] bg-[var(--admin-surface)] p-4"><div className="flex items-start justify-between gap-3"><p className="text-sm font-medium">Benefit {index + 1}</p><div className="flex gap-1"><IconButton label="Move up" disabled={!index} onClick={() => { setHomepage({ ...homepage, benefits: moveItem(homepage.benefits, index, -1) }); }} icon={<ChevronUp size={15} />} /><IconButton label="Move down" disabled={index === homepage.benefits.length - 1} onClick={() => { setHomepage({ ...homepage, benefits: moveItem(homepage.benefits, index, 1) }); }} icon={<ChevronDown size={15} />} /><IconButton label="Remove benefit" onClick={() => { setHomepage({ ...homepage, benefits: homepage.benefits.filter((_, itemIndex) => itemIndex !== index) }); }} icon={<Trash2 size={15} />} /></div></div><div className="mt-3 grid gap-3 sm:grid-cols-2"><CharacterField label="Benefit title" value={benefit.title} onChange={(value) => updateBenefit(index, "title", value)} limit={CMS_LIMITS.benefit_title} /><CharacterField label="Benefit description" value={benefit.description} onChange={(value) => updateBenefit(index, "description", value)} limit={CMS_LIMITS.benefit_description} textarea /></div></div>)}</div>{!homepage.benefits.length && <EmptyState icon={Star} title="No benefit cards yet" description="Add the first trust point for guests." compact />}</div></div>}
          {activeSection === "corporate" && <div className="mt-6 grid gap-5"><FormGroup title="Corporate stays call to action" description="Explain how furnished houses support business travellers, contractors, and project teams."><CharacterField label="Section heading" value={homepage.corporate_heading} onChange={(value) => update("corporate_heading", value, "corporate")} limit={CMS_LIMITS.section_heading} /><CharacterField label="Section description" value={homepage.corporate_description} onChange={(value) => update("corporate_description", value, "corporate")} limit={CMS_LIMITS.section_description} textarea /><div className="grid gap-4 sm:grid-cols-2"><CharacterField label="Button label" value={homepage.corporate_cta_label} onChange={(value) => update("corporate_cta_label", value, "corporate")} limit={CMS_LIMITS.button_label} /><CharacterField label="Button link" value={homepage.corporate_cta_href} onChange={(value) => update("corporate_cta_href", value, "corporate")} limit={120} /></div></FormGroup></div>}
          {activeSection === "location" && <div className="mt-6 grid gap-5"><FormGroup title="Location section" description="Introduce the Pakenham area map shown near the bottom of the homepage."><CharacterField label="Section heading" value={homepage.location_heading} onChange={(value) => update("location_heading", value, "location")} limit={CMS_LIMITS.section_heading} /><CharacterField label="Section description" value={homepage.location_description} onChange={(value) => update("location_description", value, "location")} limit={CMS_LIMITS.section_description} textarea /></FormGroup></div>}
          {activeSection === "faqs" && <div className="mt-6 grid gap-5"><FormGroup title="Frequently asked questions" description="Answer the questions guests commonly have before they choose dates and book."><CharacterField label="FAQ section heading" value={homepage.faq_heading} onChange={(value) => update("faq_heading", value, "faqs")} limit={CMS_LIMITS.section_heading} /><CharacterField label="FAQ supporting text" value={homepage.faq_description} onChange={(value) => update("faq_description", value, "faqs")} limit={CMS_LIMITS.section_description} textarea /></FormGroup><div className="rounded-xl border border-[var(--admin-border)] bg-[var(--admin-surface-alt)] p-4"><div className="flex items-start justify-between gap-3"><div><h3 className="text-lg font-semibold">Guest questions</h3><p className="mt-1 text-sm text-[var(--admin-muted)]">Keep answers plain, useful, and specific to the Serenity houses.</p></div><button type="button" className="admin-button inline-flex min-h-10 items-center gap-2 px-3 text-sm" onClick={() => { setHomepage({ ...homepage, faqs: [...homepage.faqs, { question: "", answer: "" }] }); }}><Plus size={15} /> Add question</button></div><div className="mt-4 grid gap-3">{homepage.faqs.map((faq, index) => <div key={`faq-${index}`} className="rounded-xl border border-[var(--admin-border)] bg-[var(--admin-surface)] p-4"><div className="flex items-start justify-between gap-3"><p className="text-sm font-medium">Question {index + 1}</p><div className="flex gap-1"><IconButton label="Move up" disabled={!index} onClick={() => { setHomepage({ ...homepage, faqs: moveItem(homepage.faqs, index, -1) }); }} icon={<ChevronUp size={15} />} /><IconButton label="Move down" disabled={index === homepage.faqs.length - 1} onClick={() => { setHomepage({ ...homepage, faqs: moveItem(homepage.faqs, index, 1) }); }} icon={<ChevronDown size={15} />} /><IconButton label="Remove question" onClick={() => { setHomepage({ ...homepage, faqs: homepage.faqs.filter((_, itemIndex) => itemIndex !== index) }); }} icon={<Trash2 size={15} />} /></div></div><div className="mt-3 grid gap-3"><CharacterField label="Question" value={faq.question} onChange={(value) => updateFaq(index, "question", value)} limit={140} /><CharacterField label="Answer" value={faq.answer} onChange={(value) => updateFaq(index, "answer", value)} limit={700} textarea /></div></div>)}</div>{!homepage.faqs.length && <EmptyState icon={MessageSquare} title="No FAQs yet" description="Add the first answer guests should see before booking." compact />}</div></div>}
          {activeSection === "cta" && <div className="mt-6 grid gap-5"><FormGroup title="Final booking prompt" description="Give guests a clear next step after they have read about the houses, location, and policies."><CharacterField label="CTA heading" value={homepage.final_cta_heading} onChange={(value) => update("final_cta_heading", value, "cta")} limit={CMS_LIMITS.section_heading} /><CharacterField label="CTA supporting text" value={homepage.final_cta_description} onChange={(value) => update("final_cta_description", value, "cta")} limit={CMS_LIMITS.section_description} textarea /><div className="grid gap-4 sm:grid-cols-2"><CharacterField label="Primary button label" value={homepage.final_cta_primary_label} onChange={(value) => update("final_cta_primary_label", value, "cta")} limit={CMS_LIMITS.button_label} /><CharacterField label="Button link" value={homepage.final_cta_primary_href} onChange={(value) => update("final_cta_primary_href", value, "cta")} limit={120} /><CharacterField label="Secondary button label" value={homepage.final_cta_secondary_label} onChange={(value) => update("final_cta_secondary_label", value, "cta")} limit={CMS_LIMITS.button_label} /><CharacterField label="Button link" value={homepage.final_cta_secondary_href} onChange={(value) => update("final_cta_secondary_href", value, "cta")} limit={120} /></div></FormGroup></div>}
          <div className="homepage-cms-savebar"><div><p className="text-sm font-medium">{dirtySections[activeSection] ? "Unsaved changes" : activeSection === "search" ? "No copy to save" : "Section saved"}</p><p className="text-sm text-[var(--admin-muted)]">{activeSection === "search" ? "Search behaviour is controlled by the booking flow." : "Save a draft first, or publish this homepage content when it is ready."}</p></div><div className="flex flex-wrap gap-2">{activeSection !== "search" && <><button type="button" className="admin-button inline-flex min-h-10 items-center gap-2 px-3 text-sm" disabled={saving || !dirtySections[activeSection]} onClick={() => void saveCurrent(false)}><Save size={15} /> Save draft</button><button type="button" className="admin-button admin-button-primary inline-flex min-h-10 items-center gap-2 px-3 text-sm" disabled={saving || !dirtySections[activeSection]} onClick={() => void saveCurrent(true)}><Globe2 size={15} /> {saving ? "Saving…" : "Save and publish"}</button></>}</div></div>
        </section>
      </div>
    </div>
  </>;
}

