"use client";
import { useId, useRef, useState } from "react";
import { ChevronDown, ChevronUp, Plus, X } from "lucide-react";
import { AMENITY_CATALOG, AMENITY_GROUPS, AMENITY_ICONS, normalizeAmenities, type Amenity, type AmenityGroup, type AmenityIconId } from "@/src/lib/amenities";
import { AmenityIcon } from "@/src/components/AmenityIcon";
export function AmenityEditor({ labels, details, onChange }: { labels:string[]; details:unknown; onChange:(items:Amenity[])=>void }) {
  const items=normalizeAmenities(labels,details), id=useId(), input=useRef<HTMLInputElement>(null);
  const [query,setQuery]=useState(""),[open,setOpen]=useState(false),[active,setActive]=useState(0),[customIcon,setCustomIcon]=useState<AmenityIconId>("check"),[group,setGroup]=useState<AmenityGroup>("other");
  const options=AMENITY_CATALOG.filter(a=>!items.some(i=>i.id===a.id||i.label.toLowerCase()===a.label.toLowerCase()) && `${a.label} ${AMENITY_GROUPS[a.group]}`.toLowerCase().includes(query.toLowerCase()));
  const add=(item:Amenity)=>{if(!items.some(a=>a.label.toLowerCase()===item.label.toLowerCase()||a.id===item.id))onChange([...items,item]);setQuery("");setOpen(false);input.current?.focus();};
  const move=(index:number,delta:number)=>{const next=[...items];[next[index],next[index+delta]]=[next[index+delta],next[index]];onChange(next);};
  return <section className="admin-card p-5 sm:p-7 grid gap-4"><div><h2 className="text-xl font-semibold">What this place offers</h2><p className="text-sm text-[var(--admin-muted)]">Select only amenities available at this house. Existing custom labels are kept.</p></div>
    <div className="admin-amenity-combobox" onBlur={e=>{if(!e.currentTarget.contains(e.relatedTarget))setOpen(false);}}><label htmlFor={id}>Search amenities</label><input id={id} ref={input} className="admin-field mt-1" role="combobox" aria-expanded={open} aria-controls={`${id}-options`} aria-autocomplete="list" aria-activedescendant={open&&options.length?`${id}-option-${Math.min(active,options.length-1)}`:undefined} value={query} onFocus={()=>setOpen(true)} onChange={e=>{setQuery(e.target.value);setOpen(true);setActive(0);}} onKeyDown={e=>{if(e.key==="Escape")setOpen(false);if(e.key==="ArrowDown"||e.key==="ArrowUp"){e.preventDefault();setOpen(true);setActive(n=>Math.max(0,Math.min(options.length-1,n+(e.key==="ArrowDown"?1:-1))));}if(e.key==="Enter"&&open&&options.length){e.preventDefault();add(options[Math.min(active,options.length-1)]);}}} />
    {open&&<div role="listbox" id={`${id}-options`} aria-label="Available amenities" className="admin-amenity-options">{options.map((a,i)=><div role="option" aria-selected={i===active} id={`${id}-option-${i}`} key={a.id + a.label} onMouseDown={e=>e.preventDefault()} onClick={()=>add(a)}><AmenityIcon icon={a.icon}/><span>{a.label}<small>{AMENITY_GROUPS[a.group]}</small></span></div>)}{!options.length&&<p>No matching catalog amenities. Add a custom amenity below.</p>}</div>}</div>
    <details><summary className="cursor-pointer font-medium">Add a custom amenity</summary><div className="grid gap-3 mt-3 sm:grid-cols-3"><label>Amenity name<input className="admin-field" maxLength={60} value={query} onChange={e=>setQuery(e.target.value)}/></label><label>Icon<select className="admin-field" value={customIcon} onChange={e=>setCustomIcon(e.target.value as AmenityIconId)}>{AMENITY_ICONS.map(i=><option key={i}>{i}</option>)}</select></label><label>Group<select className="admin-field" value={group} onChange={e=>setGroup(e.target.value as AmenityGroup)}>{Object.entries(AMENITY_GROUPS).map(([k,v])=><option value={k} key={k}>{v}</option>)}</select></label></div><button type="button" className="admin-button mt-3" disabled={!query.trim()||items.some(a=>a.label.toLowerCase()===query.trim().toLowerCase())} onClick={()=>add({id:`custom:${query.trim().toLowerCase()}`,label:query.trim(),icon:customIcon,group})}><AmenityIcon icon={customIcon}/><Plus size={16}/>Add custom amenity</button></details>
    <ol className="admin-selected-amenities">{items.map((a,i)=><li key={a.id + a.label}><AmenityIcon icon={a.icon}/><span>{a.label}</span><button type="button" className="admin-icon-button" disabled={!i} aria-label={`Move ${a.label} up`} onClick={()=>move(i,-1)}><ChevronUp size={16}/></button><button type="button" className="admin-icon-button" disabled={i===items.length-1} aria-label={`Move ${a.label} down`} onClick={()=>move(i,1)}><ChevronDown size={16}/></button><button type="button" className="admin-icon-button" aria-label={`Remove ${a.label}`} onClick={()=>onChange(items.filter((_,n)=>n!==i))}><X size={16}/></button></li>)}</ol>{!items.length&&<p className="text-sm text-[var(--admin-muted)]">No amenities selected.</p>}
  </section>;
}
