"use client";
import { useState } from "react";
import type { Property } from "@/src/data/properties";
import { calculatePrice, formatAud, addDays, todayIso, validateGuestCapacity } from "@/src/lib/booking";
import { NumberField, Toggle } from "./AdminFields";
import type { Row } from "./AdminModels";
export function GuestsPricingEditor({ draft,setDraft }: { draft:Row; setDraft:(update:(r:Row)=>Row)=>void }) {
  const field=(key:string,value:unknown)=>setDraft(r=>({...r,[key]:value}));
  const [nights,setNights]=useState(3),[adults,setAdults]=useState(2),[children,setChildren]=useState(0),[infants,setInfants]=useState(0),[pets,setPets]=useState(0);
  const property={nightlyPrice:Number(draft.nightly_price),cleaningFee:Number(draft.cleaning_fee),petFee:Number(draft.pet_fee),extraGuestFee:Number(draft.extra_guest_fee),extraGuestThreshold:Number(draft.extra_guest_threshold),weeklyDiscount:Number(draft.weekly_discount),monthlyDiscount:Number(draft.monthly_discount),corporateDiscount:Number(draft.corporate_discount),minimumGuests:Number(draft.minimum_guests),maxGuests:Number(draft.max_guests),maximumAdults:Number(draft.maximum_adults),maximumChildren:Number(draft.maximum_children),maximumInfants:Number(draft.maximum_infants),maximumPets:Number(draft.maximum_pets),petsAllowed:draft.pets_allowed!==false} as Property;
  const guests={adults,children,infants,pets},price=calculatePrice(property,todayIso(),addDays(todayIso(),Math.max(1,Math.min(365,nights||1))),guests),error=validateGuestCapacity(property,guests);
  return <section className="admin-card p-5 sm:p-7 grid gap-5"><div><h2 className="text-xl font-semibold">Guests and pricing</h2><p className="text-sm text-[var(--admin-muted)]">Adults and children are staying guests. Infants do not count toward capacity or extra-guest fees and have their own limit.</p></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{[["Minimum staying guests","minimum_guests"],["Maximum staying guests","max_guests"],["Maximum adults","maximum_adults"],["Maximum children","maximum_children"],["Maximum infants","maximum_infants"],["Maximum pets","maximum_pets"],["Guests included in default rate","extra_guest_threshold"],["Extra guest / night (AUD)","extra_guest_fee"],["Pet fee / stay (AUD)","pet_fee"],["Cleaning fee / stay (AUD)","cleaning_fee"]].map(([label,key])=><NumberField key={key} label={label} value={draft[key]} onChange={v=>field(key,v)} />)}</div><div className="flex flex-wrap gap-5"><Toggle label="Children allowed" checked={Number(draft.maximum_children)>0} onChange={v=>field("maximum_children",v?1:0)}/><Toggle label="Infants allowed" checked={Number(draft.maximum_infants)>0} onChange={v=>field("maximum_infants",v?1:0)}/><Toggle label="Pets allowed" checked={draft.pets_allowed!==false} onChange={v=>setDraft(r=>({...r,pets_allowed:v,maximum_pets:v?Math.max(1,Number(r.maximum_pets)):0}))}/></div><p className="text-sm text-[var(--admin-muted)]">Extra-guest fee = staying guests above the included count × fee × nights. The pet fee is charged once per stay if one or more pets stay, regardless of pet count. Cleaning is once per stay. The existing 10% tax calculation and stay discounts remain unchanged.</p>
  <details open className="rounded-xl border border-[var(--admin-border)] p-4"><summary className="font-medium cursor-pointer">Live example at the default rate</summary><div className="grid gap-3 my-4 grid-cols-2 lg:grid-cols-5">{[["Nights",nights,setNights],["Adults",adults,setAdults],["Children",children,setChildren],["Infants",infants,setInfants],["Pets",pets,setPets]].map(([label,value,setter])=><label key={String(label)}>{String(label)}<input className="admin-field" type="number" min={label==="Nights"?1:0} max="365" value={Number(value)} onChange={e=>(setter as (n:number)=>void)(Number(e.target.value))}/></label>)}</div>{error&&<p className="admin-notice is-error" role="status">{error}</p>}<dl className="admin-example-price">{[["Accommodation",price.nightlySubtotal],["Extra guests",price.extraGuestFee],["Pet fee",price.petFee],["Cleaning",price.cleaningFee],["Stay discount",-price.discount],["Tax",price.tax],["Total",price.total]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{formatAud(Number(value))}</dd></div>)}</dl><p className="text-sm text-[var(--admin-muted)]">Illustration only. Date overrides and promotion codes are not included in this example.</p></details></section>;
}
