"use client";
import { useState } from "react";
import { ChevronLeft, ChevronRight } from "lucide-react";
import { applyDateRates, pricingDates, type DateRate } from "@/src/lib/date-pricing";
import { formatAud, formatDateAu, todayIso } from "@/src/lib/booking";
import { useDirtyGuard } from "./AdminUI";
export function PricingCalendar({ datePrices, defaultRate, onChange, onDefaultChange }: { datePrices:DateRate[]; defaultRate:number; onChange:(prices:DateRate[])=>void; onDefaultChange:(price:number)=>void }) {
  const [month,setMonth]=useState(()=>todayIso().slice(0,7)),[start,setStart]=useState(""),[end,setEnd]=useState(""),[rate,setRate]=useState(String(defaultRate)),[label,setLabel]=useState(""),[error,setError]=useState(""),[message,setMessage]=useState(""),[editing,setEditing]=useState(false);
  useDirtyGuard(editing);
  const first=new Date(`${month}-01T00:00:00Z`),offset=(first.getUTCDay()+6)%7,days=new Date(Date.UTC(first.getUTCFullYear(),first.getUTCMonth()+1,0)).getUTCDate();
  const navigate=(delta:number)=>setMonth(new Date(Date.UTC(first.getUTCFullYear(),first.getUTCMonth()+delta,1)).toISOString().slice(0,7));
  const pick=(date:string)=>{setMessage("");if(!start||end){const existing=datePrices.find(p=>p.price_date===date&&p.is_active!==false);setStart(date);setEnd("");setRate(String(existing?.nightly_price??defaultRate));setLabel(existing?.label??"");setEditing(false);}else{setStart(date<start?date:start);setEnd(date<start?start:date);}};
  const commit=(reset=false)=>{try{const next=applyDateRates(datePrices,start,end||start,reset?null:Number(rate),label);if(!reset&&!rate.trim())throw new Error("Enter a nightly rate.");onChange(next);setEditing(false);setError("");setMessage(`${pricingDates(start,end||start).length} night(s) ${reset?"reset to default":"updated"} in the house draft. Save changes below to persist.`);}catch(e){setError(e instanceof Error?e.message:"Could not update dates.");}};
  return <section className="admin-card p-5 sm:p-7 grid gap-5"><div><h2 className="text-xl font-semibold">Nightly pricing calendar</h2><p className="text-sm text-[var(--admin-muted)]">Every night uses the default unless you add a special rate. Pricing does not block availability.</p></div><label className="max-w-sm">Default nightly rate (AUD)<input className="admin-field mt-1" type="number" min="0" step="0.01" value={defaultRate} onChange={e=>onDefaultChange(Number(e.target.value))}/><span className="text-sm text-[var(--admin-muted)]">Changing this rate preserves all explicit overrides.</span></label>
    <div className="flex items-center justify-between gap-3"><button type="button" className="admin-icon-button" aria-label="Previous pricing month" onClick={()=>navigate(-1)}><ChevronLeft/></button><label className="text-center"><span className="sr-only">Pricing month</span><input className="admin-field" type="month" value={month} onChange={e=>{if(/^\d{4}-\d{2}$/.test(e.target.value))setMonth(e.target.value);}}/></label><button type="button" className="admin-icon-button" aria-label="Next pricing month" onClick={()=>navigate(1)}><ChevronRight/></button></div>
    <div className="admin-rate-calendar" aria-label="Nightly rates">{["Mon","Tue","Wed","Thu","Fri","Sat","Sun"].map(d=><span className="admin-rate-weekday" key={d}>{d}</span>)}{Array.from({length:offset},(_,i)=><span key={`blank-${i}`}/>)}{Array.from({length:days},(_,i)=>{const date=`${month}-${String(i+1).padStart(2,"0")}`,override=datePrices.find(p=>p.price_date===date&&p.is_active!==false),selected=date>=start&&date<=(end||start);return <button type="button" key={date} aria-pressed={selected} className="admin-rate-day" data-selected={selected} data-override={!!override} aria-label={`${formatDateAu(date)}, ${formatAud(override?.nightly_price??defaultRate)}, ${override?`special rate ${override.label??""}`:"default rate"}`} onClick={()=>pick(date)}><b>{i+1}</b><span>{formatAud(override?.nightly_price??defaultRate)}</span>{override&&<small aria-hidden="true">•</small>}</button>;})}</div>
    <p className="text-sm text-[var(--admin-muted)]">• Special rate. Select a night, then optionally select the last night of a range. Both selected dates are nights charged; a booking’s checkout date is excluded.</p>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><label>First night<input type="date" className="admin-field" value={start} onChange={e=>setStart(e.target.value)}/></label><label>Last night (inclusive)<input type="date" className="admin-field" value={end||start} min={start} onChange={e=>setEnd(e.target.value)}/></label><label>Special rate (AUD/night)<input type="number" className="admin-field" min="0" step="0.01" value={rate} onChange={e=>{setRate(e.target.value);setEditing(true);}}/></label><label>Label (optional)<input className="admin-field" maxLength={120} placeholder="Christmas" value={label} onChange={e=>{setLabel(e.target.value);setEditing(true);}}/></label></div>
    {start&&<p role="status">Selected: {formatDateAu(start)}{end&&end!==start?` – ${formatDateAu(end)}`:""} (nights).</p>}
    <div className="flex flex-wrap gap-2"><button type="button" disabled={!start} className="admin-button admin-button-primary" onClick={()=>commit()}>Apply rate to draft</button><button type="button" disabled={!start} className="admin-button" onClick={()=>commit(true)}>Reset to default</button><button type="button" className="admin-button" onClick={()=>{setStart("");setEnd("");setRate(String(defaultRate));setLabel("");setEditing(false);setError("");setMessage("Selection cancelled. Applied house draft changes remain until saved or discarded.");}}>Cancel selection</button></div>{error&&<p role="alert" className="admin-notice is-error">{error}</p>}{message&&<p role="status" className="admin-notice">{message}</p>}
  </section>;
}
