"use client";
import { useState } from "react";
import { Plus, Save, Star } from "lucide-react";
import { REVIEW_CATEGORIES, reviewRatingErrors, normalizeCategoryRatings } from "@/src/lib/review-ratings";
import { CMS_LIMITS } from "@/src/lib/cmsValidation";
import { CharacterField, PageHeader } from "./AdminFields";
import { AdminBadge, useAdminPagination, useAdminWorkspace, useDirtyGuard } from "./AdminUI";
import type { Row } from "./AdminModels";
export function ReviewManager({ properties,reviews,createReview,updateReview,deleteReview }: { properties:Row[];reviews:Row[];createReview:(r:Row)=>Promise<void>;updateReview:(id:string,r:Row)=>Promise<void>;deleteReview:(id:string)=>Promise<void> }) {
 const {confirm}=useAdminWorkspace(),[propertyId,setPropertyId]=useState(String(properties[0]?.id??"")),[query,setQuery]=useState(""),[draft,setDraft]=useState<Row|null>(null),[baseline,setBaseline]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const dirty=!!draft&&JSON.stringify(draft)!==baseline;useDirtyGuard(dirty||busy);
 const filtered=reviews.filter(r=>r.property_id===propertyId&&`${r.reviewer_name} ${r.review_text}`.toLowerCase().includes(query.toLowerCase())),{visible,pagination}=useAdminPagination(filtered);
 const leave=async()=>!dirty||await confirm({title:"Discard review edits?",description:"Unsaved review changes will be lost.",confirmLabel:"Discard edits",destructive:true});
 const edit=async(r:Row)=>{if(!await leave())return;const next={...r,rating:Number(r.rating??5),category_ratings:normalizeCategoryRatings(r.category_ratings)};setDraft(next);setBaseline(JSON.stringify(next));setError("");};
 const field=(key:string,value:unknown)=>setDraft(r=>r?{...r,[key]:value}:r);
 const save=async(e:React.FormEvent)=>{e.preventDefault();if(!draft)return;const errors=reviewRatingErrors(Number(draft.rating),draft.category_ratings);if(errors.length){setError(errors.join(" "));return;}setBusy(true);try{const payload={...draft,property_id:propertyId};if(draft.id)await updateReview(String(draft.id),payload);else await createReview(payload);setDraft(null);setError("");}catch(e){setError(e instanceof Error?e.message:"Could not save review.");}finally{setBusy(false);}};
 return <><PageHeader eyebrow="Reviews" title="Manage guest reviews" description="Record the ratings guests actually gave. Category scores are optional." action={<button type="button" className="admin-button admin-button-primary" disabled={!propertyId} onClick={()=>void edit({reviewer_name:"",review_text:"",review_date:"",review_date_label:"",rating:5,category_ratings:{},published:true,display_order:filtered.length+1})}><Plus size={16}/>Add review</button>}/><div className="grid gap-4 mb-5 sm:grid-cols-2"><label>House<select className="admin-field" value={propertyId} onChange={async e=>{const id=e.target.value;if(await leave()){setPropertyId(id);setDraft(null);}}}>{properties.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Search reviews<input className="admin-field" value={query} onChange={e=>setQuery(e.target.value)}/></label></div>{error&&<p role="alert" className="admin-notice is-error">{error}</p>}
 {draft&&<form className="admin-card p-5 sm:p-7 grid gap-5 mb-5" onSubmit={save}><h2 className="text-xl font-semibold">{draft.id?"Edit review":"New review"}</h2><div className="grid gap-4 sm:grid-cols-2"><CharacterField label="Reviewer name *" value={draft.reviewer_name} onChange={v=>field("reviewer_name",v)} limit={CMS_LIMITS.reviewer_name}/><label>Overall rating<select className="admin-field" value={draft.rating} onChange={e=>field("rating",Number(e.target.value))}>{[5,4,3,2,1].map(n=><option key={n} value={n}>{n} / 5</option>)}</select></label><CharacterField label="Review date" type="date" value={draft.review_date} onChange={v=>field("review_date",v)}/><CharacterField label="Date label" value={draft.review_date_label} onChange={v=>field("review_date_label",v)} limit={CMS_LIMITS.review_date_label}/></div><CharacterField label="Review text *" value={draft.review_text} onChange={v=>field("review_text",v)} limit={CMS_LIMITS.review_text} textarea/>
 <fieldset><legend className="font-medium">Category ratings (optional)</legend><p className="text-sm text-[var(--admin-muted)]">Leave unreported scores blank. They are excluded from category averages.</p><div className="grid gap-4 mt-3 sm:grid-cols-2 lg:grid-cols-3">{Object.entries(REVIEW_CATEGORIES).map(([key,label])=><label key={key}>{label}<select className="admin-field" value={draft.category_ratings?.[key]??""} onChange={e=>{const next={...draft.category_ratings};if(e.target.value)next[key]=Number(e.target.value);else delete next[key];field("category_ratings",next);}}><option value="">Not provided</option>{[5,4,3,2,1].map(n=><option value={n} key={n}>{n} / 5</option>)}</select></label>)}</div></fieldset><label>Display order<input className="admin-field max-w-xs" type="number" min="0" step="1" value={draft.display_order??0} onChange={e=>field("display_order",Number(e.target.value))}/></label><label className="flex gap-2"><input type="checkbox" checked={draft.published!==false} onChange={e=>field("published",e.target.checked)}/>Published on website</label><div className="flex gap-2"><button disabled={busy} className="admin-button admin-button-primary"><Save size={16}/>{busy?"Saving…":"Save review"}</button><button type="button" className="admin-button" disabled={busy} onClick={async()=>{if(await leave())setDraft(null);}}>Cancel</button></div></form>}
 <div className="grid gap-4 lg:grid-cols-2">{visible.map(r=><article className="admin-card p-5 grid gap-3" key={r.id}><div className="flex justify-between gap-3"><h3>{r.reviewer_name}</h3><span className="inline-flex items-center gap-1"><Star size={16}/>{Number(r.rating)} / 5</span></div><AdminBadge domain="content" value={r.published?"published":"draft"}/><p className="whitespace-pre-line">{r.review_text}</p><div className="flex gap-2"><button className="admin-button" type="button" onClick={()=>void edit(r)}>Edit review</button><button className="admin-button" type="button" disabled={busy} onClick={async()=>{if(!await confirm({title:"Delete review?",description:"This review will be permanently removed.",confirmLabel:"Delete review",destructive:true}))return;setBusy(true);try{await deleteReview(r.id);}catch(e){setError(e instanceof Error?e.message:"Could not delete review.");}finally{setBusy(false);}}}>Delete</button></div></article>)}</div>{!filtered.length&&<p className="admin-card p-8">No reviews match this house and search.</p>}{pagination}</>;
}
