"use client";
import { BedDouble, ChevronDown, ChevronUp, Plus, X } from "lucide-react";
import { BED_TYPES, roomBedLabel, roomTotals, type BedType, type RoomArrangement } from "@/src/lib/rooms";
export function RoomsEditor({ rooms, photos, onChange }: { rooms:RoomArrangement[]; photos:{src:string;label:string}[]; onChange:(rooms:RoomArrangement[])=>void }) {
  const update=(i:number,patch:Partial<RoomArrangement>)=>onChange(rooms.map((r,n)=>n===i?{...r,...patch}:r));
  const move=(i:number,d:number)=>{const next=[...rooms];[next[i],next[i+d]]=[next[i+d],next[i]];onChange(next);};
  const totals=roomTotals(rooms);
  return <section className="admin-card p-5 sm:p-7 grid gap-4"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="text-xl font-semibold">Where you’ll sleep</h2><p className="text-sm text-[var(--admin-muted)]">Keep legacy descriptions, or choose structured bed types for each room.</p></div><button type="button" className="admin-button" onClick={()=>onChange([...rooms,{room:`Bedroom ${rooms.length+1}`,beds:"",kind:"bedroom",bedTypes:[{type:"queen",quantity:1}]}])}><Plus size={16}/>Add room</button></div>
  {rooms.map((room,i)=><fieldset key={i} className="rounded-xl border border-[var(--admin-border)] p-4 grid gap-4"><legend className="px-2 font-medium">{room.room||`Room ${i+1}`}</legend><div className="flex flex-wrap items-center gap-2"><BedDouble/><span className="mr-auto">{roomBedLabel(room)||"Add bed details"}</span><button type="button" className="admin-icon-button" disabled={!i} aria-label={`Move room ${i+1} up`} onClick={()=>move(i,-1)}><ChevronUp size={16}/></button><button type="button" className="admin-icon-button" disabled={i===rooms.length-1} aria-label={`Move room ${i+1} down`} onClick={()=>move(i,1)}><ChevronDown size={16}/></button><button type="button" className="admin-icon-button" aria-label={`Remove room ${i+1}`} onClick={()=>onChange(rooms.filter((_,n)=>n!==i))}><X size={16}/></button></div>
  <div className="grid gap-3 sm:grid-cols-2"><label>Room name<input className="admin-field" maxLength={80} value={room.room} onChange={e=>update(i,{room:e.target.value})}/></label><label>Room type<select className="admin-field" value={room.kind??""} onChange={e=>update(i,{kind:e.target.value as "bedroom"|"other"})}><option value="" disabled>Not specified (legacy)</option><option value="bedroom">Bedroom</option><option value="other">Other sleeping space</option></select></label></div>
  {room.bedTypes?.length ? <div className="grid gap-3">{room.bedTypes.map((bed,b)=><div key={b} className="flex flex-wrap items-end gap-3"><label className="flex-1">Bed type<select className="admin-field" value={bed.type} onChange={e=>update(i,{bedTypes:room.bedTypes!.map((v,n)=>n===b?{...v,type:e.target.value as BedType}:v)})}>{Object.entries(BED_TYPES).map(([k,v])=><option value={k} key={k}>{v}</option>)}</select></label><label className="w-24">Quantity<input className="admin-field" type="number" min="1" max="30" step="1" value={bed.quantity} onChange={e=>update(i,{bedTypes:room.bedTypes!.map((v,n)=>n===b?{...v,quantity:Number(e.target.value)}:v)})}/></label><button type="button" className="admin-icon-button" aria-label={`Remove bed type ${b+1} from room ${i+1}`} disabled={room.bedTypes!.length===1} onClick={()=>update(i,{bedTypes:room.bedTypes!.filter((_,n)=>n!==b)})}><X size={16}/></button></div>)}<button type="button" className="admin-button justify-self-start" onClick={()=>update(i,{bedTypes:[...room.bedTypes!,{type:"single",quantity:1}]})}>Add bed type</button></div> : <><label>Existing bed description<input className="admin-field" maxLength={300} value={room.beds} onChange={e=>update(i,{beds:e.target.value})}/></label><button type="button" className="admin-button justify-self-start" onClick={()=>update(i,{bedTypes:[{type:"single",quantity:1}]})}>Use structured beds (choose type and quantity)</button></>}
  {room.beds&&room.bedTypes?.length&&<p className="text-sm text-[var(--admin-muted)]">Previous description: {room.beds}</p>}
  <label>Room photo (optional)<select className="admin-field" value={room.photo??""} onChange={e=>update(i,{photo:e.target.value})}><option value="">No room photo</option>{room.photo&&!photos.some(p=>p.src===room.photo)&&<option value={room.photo}>Current saved photo</option>}{photos.map(p=><option key={p.src} value={p.src}>{p.label}</option>)}</select><span className="text-sm text-[var(--admin-muted)]">Choose from uploaded gallery photos.</span></label><label>Short description (optional)<textarea className="admin-field" maxLength={300} value={room.description??""} onChange={e=>update(i,{description:e.target.value})}/></label></fieldset>)}
  <p className="text-sm text-[var(--admin-muted)]">{totals?`Summary on save: ${totals.bedrooms} bedrooms · ${totals.beds} beds.`:"Bedroom and bed totals remain as entered until all rooms have structured beds and a room type."}</p></section>;
}
