"use client";
import { useState } from "react";
import { Check, KeyRound, MapPin, MessageCircle, Sparkles, Star, Tag } from "lucide-react";
import type { PropertyReview } from "@/src/data/properties";
import { aggregateReviews, validRating } from "@/src/lib/review-ratings";
import { Modal } from "@/src/components/UI";
import { isCalendarDate } from "@/src/lib/date-pricing";
const categoryIcons={cleanliness:Sparkles,accuracy:Check,check_in:KeyRound,communication:MessageCircle,location:MapPin,value:Tag};
function ReviewCard({review}:{review:PropertyReview}) {return <article className="stay-review-card"><div className="stay-review-person"><span className="stay-avatar" aria-hidden="true">{review.reviewerName.slice(0,1)}</span><div><h3>{review.reviewerName}</h3><span>{review.reviewDateLabel || (review.reviewDate && isCalendarDate(review.reviewDate.slice(0,10)) ? new Intl.DateTimeFormat("en-AU",{month:"long",year:"numeric",timeZone:"UTC"}).format(new Date(review.reviewDate.slice(0,10)+"T00:00:00Z")):"")}</span></div><span className="stay-review-score"><Star size={14} fill="currentColor"/>{review.rating}/5</span></div><p>{review.reviewText}</p></article>;}
export function PropertyReviews({reviews}:{reviews:PropertyReview[]}) {
 const [open,setOpen]=useState(false),[query,setQuery]=useState("");const published=reviews.filter(r=>r.published && validRating(r.rating)),summary=aggregateReviews(published),filtered=published.filter(r=>`${r.reviewerName} ${r.reviewText}`.toLowerCase().includes(query.toLowerCase()));
 if(!summary.count)return <section className="stay-section" id="reviews"><h2>Guest reviews</h2><p>No published reviews yet.</p></section>;
 return <section className="stay-section" id="reviews"><div className="stay-section-title"><h2><Star size={25} fill="currentColor"/>{summary.average!.toFixed(2)} · {summary.count} review{summary.count===1?"":"s"}</h2></div><div className="stay-review-overview"><div className="stay-rating-distribution"><h3>Overall rating</h3>{summary.distribution.map(d=><div key={d.stars} aria-label={`${d.stars} stars: ${d.count} reviews`}><span>{d.stars}</span><span className="stay-rating-track"><span style={{width:`${100*d.count/summary.count}%`}}/></span><small>{d.count}</small></div>)}</div><div className="stay-category-ratings">{summary.categories.map(c=>{const Icon=categoryIcons[c.key];return <div key={c.key}><Icon size={25} strokeWidth={1.5}/><h3>{c.label}</h3><strong>{c.average===null?"—":c.average.toFixed(2)}</strong><small>{c.count?`${c.count} rating${c.count===1?"":"s"}`:"Not yet rated"}</small></div>;})}</div></div><div className="stay-review-grid">{published.slice(0,4).map(r=><ReviewCard key={r.id} review={r}/>)}</div>{published.length>4&&<button type="button" className="stay-button" onClick={()=>setOpen(true)}>Show all {summary.count} reviews</button>}<Modal title="All guest reviews" open={open} onClose={()=>setOpen(false)}><label>Search reviews<input className="field mt-2 mb-5" value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="stay-review-grid">{filtered.map(r=><ReviewCard key={r.id} review={r}/>)}</div>{!filtered.length&&<p>No reviews match your search.</p>}</Modal></section>;
}
