/* eslint-disable @typescript-eslint/no-require-imports -- These local Node CommonJS tools load CommonJS runtimes. */
/* Exercise actual pure TypeScript modules without adding a runtime dependency. */
const {test}=require('node:test'), assert=require('node:assert/strict'), fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),ts=require('typescript');
const cache=new Map();
function load(relative){const file=path.resolve(__dirname,'..',relative);if(cache.has(file))return cache.get(file);const testModule={exports:{}};cache.set(file,testModule.exports);const source=ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;new Function('require','module','exports',source)(name=>name.startsWith('@/')?load(name.slice(2)+'.ts'):require(name),testModule,testModule.exports);return testModule.exports;}
const {applyDateRates,pricingDates,isCalendarDate}=load('src/lib/date-pricing.ts');
const {calculatePrice,getNightlyPrice,validateGuestCapacity,datesInRange,formatAud}=load('src/lib/booking.ts');
const {normalizeAmenities}=load('src/lib/amenities.ts');
const {normalizeRooms,roomBedLabel,roomPhoto,roomTotals,validateRooms}=load('src/lib/rooms.ts');
const {aggregateReviews,reviewRatingErrors,normalizeCategoryRatings}=load('src/lib/review-ratings.ts');
const {validatePropertyContent}=load('src/lib/cmsValidation.ts');
const {adminThemeBootstrap}=load('src/lib/admin-theme.ts');
const property={name:'Test house',nightlyPrice:200,datePrices:[],cleaningFee:50,petFee:40,extraGuestThreshold:2,extraGuestFee:20,weeklyDiscount:10,monthlyDiscount:20,corporateDiscount:15,minimumGuests:1,maxGuests:6,maximumAdults:6,maximumChildren:4,maximumInfants:2,maximumPets:2,petsAllowed:true};
const guests={adults:2,children:0,infants:0,pets:0};
const mapped=rates=>rates.map(r=>({date:r.price_date,nightlyPrice:r.nightly_price,label:r.label,active:r.is_active}));
test('currency displays configured cents without rounding a nightly rate to dollars',()=>{assert.equal(formatAud(240),'$240');assert.equal(formatAud(240.50),'$240.50');});
test('default-only quotes retain fees and tax',()=>{const p=calculatePrice(property,'2026-12-23','2026-12-27',guests);assert.equal(p.nightlySubtotal,800);assert.equal(p.tax,85);assert.equal(p.total,935);assert.equal(p.nightlyRates.length,4);});
test('single override can be edited and reset without touching other dates',()=>{let r=applyDateRates([],'2026-12-24','2026-12-24',300,'Holiday');r=applyDateRates(r,'2026-12-25','2026-12-25',350);r=applyDateRates(r,'2026-12-24','2026-12-24',325);assert.equal(r[0].nightly_price,325);r=applyDateRates(r,'2026-12-24','2026-12-24',null);assert.deepEqual(r.map(x=>x.price_date),['2026-12-25']);});
test('Christmas 24–26 is inclusive for rates, exclusive at booking checkout',()=>{const rates=applyDateRates([],'2026-12-24','2026-12-26',300,'Christmas');assert.deepEqual(rates.map(r=>r.price_date),['2026-12-24','2026-12-25','2026-12-26']);const p={...property,datePrices:mapped(rates)};assert.equal(calculatePrice(p,'2026-12-23','2026-12-27',guests).nightlySubtotal,1100);assert.equal(calculatePrice(p,'2026-12-23','2026-12-26',guests).nightlySubtotal,800);});
test('default rate changes preserve explicit prices, zero override and inactive fallback',()=>{const p={...property,nightlyPrice:250,datePrices:[{date:'2026-12-24',nightlyPrice:300},{date:'2026-12-25',nightlyPrice:0},{date:'2026-12-26',nightlyPrice:900,active:false}]};assert.equal(getNightlyPrice(p,'2026-12-23'),250);assert.equal(getNightlyPrice(p,'2026-12-24'),300);assert.equal(getNightlyPrice(p,'2026-12-25'),0);assert.equal(getNightlyPrice(p,'2026-12-26'),250);});
test('date ranges survive Australian daylight saving and reject invalid dates',()=>{assert.deepEqual(pricingDates('2026-10-03','2026-10-05'),['2026-10-03','2026-10-04','2026-10-05']);assert.deepEqual(datesInRange('2026-10-03','2026-10-05'),['2026-10-03','2026-10-04']);assert.equal(isCalendarDate('2026-02-29'),false);assert.equal(isCalendarDate('2028-02-29'),true);assert.throws(()=>pricingDates('2026-12-26','2026-12-24'));assert.throws(()=>pricingDates('2026-01-01','2029-01-01'));assert.throws(()=>applyDateRates([],'2026-12-24','2026-12-24',NaN));assert.throws(()=>applyDateRates([],'2026-12-24','2026-12-24',-1));});
test('extra guests count adults and children per night; pet fee is once and infants excluded',()=>{const p=calculatePrice(property,'2026-12-01','2026-12-04',{adults:3,children:1,infants:2,pets:2});assert.equal(p.extraGuestFee,120);assert.equal(p.petFee,40);assert.equal(p.total,891);});
test('stay discounts apply to accommodation only, preserving corporate and tax basis',()=>{const p=calculatePrice(property,'2026-12-01','2026-12-08',{...guests,pets:1},true);assert.equal(p.discount,210);assert.equal(p.tax,128);assert.equal(p.total,1408);assert.equal(calculatePrice(property,'2026-12-01','2026-12-29',guests).discount,1120);});
test('guest validation enforces totals, each category, allowed flags and whole counts',()=>{assert.equal(validateGuestCapacity(property,{adults:4,children:2,infants:2,pets:2}),'');for(const g of [{adults:0},{adults:7},{children:5},{infants:3},{pets:3},{adults:1.5},{children:-1},{adults:NaN}])assert.notEqual(validateGuestCapacity(property,{...guests,...g}),'');assert.notEqual(validateGuestCapacity({...property,petsAllowed:false},{...guests,pets:1}),'');assert.notEqual(validateGuestCapacity({...property,maximumChildren:0},{...guests,children:1}),'');assert.notEqual(validateGuestCapacity({...property,minimumGuests:3},guests),'');});
test('CMS rejects contradictory capacity, invalid room data, duplicate or invalid rates',()=>{for(const change of [{minimum_guests:7,max_guests:6},{maximum_adults:7,max_guests:6},{minimum_guests:5,maximum_adults:2,maximum_children:2},{extra_guest_fee:-1},{date_prices:[{price_date:'2026-02-30',nightly_price:200}]},{date_prices:[{price_date:'2026-12-24',nightly_price:200},{price_date:'2026-12-24',nightly_price:300}]},{bed_arrangements:[{room:'Room',bedTypes:[{type:'invented',quantity:1}]}]}])assert.ok(validatePropertyContent(change).length);});
test('amenities retain unknown labels and explicit allowlisted metadata',()=>{const result=normalizeAmenities(['Wi-Fi','Unusual amenity','wi-fi'],[{label:'Unusual amenity',id:'custom:stable',icon:'trees',group:'outdoor'}]);assert.equal(result.length,2);assert.equal(result[0].id,'wifi');assert.deepEqual(result[1],{label:'Unusual amenity',id:'custom:stable',icon:'trees',group:'outdoor'});const safe=normalizeAmenities(['Custom'],[{label:'Custom',icon:'<script>',group:'__proto__'}])[0];assert.equal(safe.icon,'check');assert.equal(safe.group,'other');});
test('legacy room labels survive with no invented types or derived totals',()=>{const old=[{room:'Bedroom',beds:'One large bed and a spare mattress'}];assert.deepEqual(normalizeRooms(old),old);assert.equal(roomBedLabel(old[0]),old[0].beds);assert.equal(roomTotals(old),null);assert.deepEqual(validateRooms(old),[]);});
test('structured rooms persist photos/details and derive total beds and bedrooms',()=>{const rooms=[{room:'Bedroom',beds:'',kind:'bedroom',bedTypes:[{type:'queen',quantity:1},{type:'single',quantity:2}],photo:'/bedroom.jpg',description:'Garden-facing'},{room:'Lounge',beds:'',kind:'other',bedTypes:[{type:'sofa',quantity:1}]}];assert.deepEqual(normalizeRooms(rooms),rooms);assert.deepEqual(roomTotals(rooms),{bedrooms:1,beds:4});assert.deepEqual(validateRooms(rooms),[]);assert.ok(validateRooms([{room:'Bad',bedTypes:[{type:'constructor',quantity:1}]}]).length);assert.ok(validateRooms([{room:'Bad',photo:'javascript:alert(1)'}]).length);});
test('room cards use matching gallery photos without confusing numbered bedrooms',()=>{const images=[{src:'/bedroom-11.jpg',categoryLabel:'Bedroom 11'},{src:'/bedroom-2.jpg',category:'bedroom-2'},{src:'/bedroom-1.jpg',alt:'Serenity 7 bedroom 1 image 1'},{src:'/lounge.jpg',categoryLabel:'Living room'}];assert.equal(roomPhoto({room:'Bedroom 1',beds:''},images),'/bedroom-1.jpg');assert.equal(roomPhoto({room:'Bedroom 2',beds:''},images),'/bedroom-2.jpg');assert.equal(roomPhoto({room:'Bedroom 3',beds:''},images),undefined);assert.equal(roomPhoto({room:'Bedroom 1',beds:'',photo:'/selected.jpg'},images),'/selected.jpg');});
test('review aggregates use published actual scores and exclude missing category values',()=>{const s=aggregateReviews([{published:true,rating:5,categoryRatings:{cleanliness:4,value:3}},{published:true,rating:3,categoryRatings:{cleanliness:2}},{published:true,rating:4},{published:false,rating:1,categoryRatings:{cleanliness:1}}]);assert.equal(s.count,3);assert.equal(s.average,4);assert.deepEqual(s.distribution.map(r=>r.count),[1,1,1,0,0]);assert.equal(s.categories[0].average,3);assert.equal(s.categories[0].count,2);assert.equal(s.categories.find(c=>c.key==='value').average,3);assert.equal(s.categories.find(c=>c.key==='accuracy').average,null);});
test('legacy reviews need no category scores, new scores must be integers 1–5',()=>{assert.deepEqual(reviewRatingErrors(4,undefined),[]);assert.deepEqual(reviewRatingErrors(5,{}),[]);for(const n of [0,6,2.5,'5',null])assert.ok(reviewRatingErrors(n,{}).length);for(const c of [{cleanliness:0},{value:6},{value:4.5},{constructor:5},[]])assert.ok(reviewRatingErrors(5,c).length);assert.deepEqual(normalizeCategoryRatings({value:4,cleanliness:null,unknown:5}),{value:4});assert.equal(aggregateReviews([]).average,null);});
function bootstrap(stored,system,storageFailure=false){const rules=['base','media'],writes=[];const context={document:{getElementById:()=>({sheet:{cssRules:rules,insertRule:(r,i)=>rules.splice(i,0,r)}})},localStorage:{getItem:()=>{if(storageFailure)throw Error('blocked');return stored;},setItem:(...args)=>writes.push(args)},matchMedia:()=>({matches:system})};vm.runInNewContext(adminThemeBootstrap,context);return {rule:rules[2],writes};}
test('theme initialization honors explicit choices over system and migrates night',()=>{assert.match(bootstrap('light',true).rule,/--serenity-theme:light/);assert.match(bootstrap('dark',false).rule,/--serenity-theme:dark/);const legacy=bootstrap('night',false);assert.match(legacy.rule,/--serenity-theme:dark/);assert.deepEqual(legacy.writes,[['serenity-admin-theme','dark']]);});
test('theme initialization uses system without storage and reveals only initialized admin',()=>{assert.match(bootstrap(null,true).rule,/--serenity-theme:dark/);assert.match(bootstrap(null,false,true).rule,/--serenity-theme:light/);assert.match(bootstrap(null,true,true).rule,/visibility:visible/);});
